"""initial schema

Revision ID: 16ede39998d6
Revises: 
Create Date: 2026-04-13 12:20:10.160847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ede39998d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aziende',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ragione_sociale', sa.String(), nullable=False),
    sa.Column('sede_legale_via', sa.String(), nullable=True),
    sa.Column('sede_legale_citta', sa.String(), nullable=True),
    sa.Column('sede_operativa_via', sa.String(), nullable=True),
    sa.Column('sede_operativa_citta', sa.String(), nullable=True),
    sa.Column('attivita', sa.Text(), nullable=True),
    sa.Column('codice_ateco', sa.String(), nullable=True),
    sa.Column('orario_lavoro', sa.String(), nullable=True),
    sa.Column('metratura_totale', sa.Numeric(), nullable=True),
    sa.Column('zona_sismica', sa.Integer(), nullable=True),
    sa.Column('descrizione_attivita', sa.Text(), nullable=True),
    sa.Column('contesto_territoriale', sa.Text(), nullable=True),
    sa.Column('survey_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attrezzature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('azienda_id', sa.UUID(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('marcatura_ce', sa.Boolean(), nullable=False),
    sa.Column('verifiche_periodiche', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documenti_generati',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('azienda_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('versione', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('gdrive_file_id', sa.String(), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('azienda_id', sa.UUID(), nullable=False),
    sa.Column('nominativo', sa.String(), nullable=False),
    sa.Column('codice_fiscale', sa.String(), nullable=True),
    sa.Column('mansione', sa.String(), nullable=True),
    sa.Column('tipologia_contrattuale', sa.String(), nullable=True),
    sa.Column('sesso', sa.String(), nullable=True),
    sa.Column('fascia_eta', sa.String(), nullable=True),
    sa.Column('ruolo_rspp', sa.Boolean(), nullable=False),
    sa.Column('ruolo_rls', sa.Boolean(), nullable=False),
    sa.Column('ruolo_primo_soccorso', sa.Boolean(), nullable=False),
    sa.Column('ruolo_antincendio', sa.Boolean(), nullable=False),
    sa.Column('ruolo_preposto', sa.Boolean(), nullable=False),
    sa.Column('ruolo_datore_lavoro', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sostanze_chimiche',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('azienda_id', sa.UUID(), nullable=False),
    sa.Column('nome_prodotto', sa.String(), nullable=False),
    sa.Column('produttore', sa.String(), nullable=True),
    sa.Column('attivita_uso', sa.Text(), nullable=True),
    sa.Column('pittogrammi', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stato_miscela', sa.String(), nullable=True),
    sa.Column('frasi_h', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('frasi_p', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_extracted', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(), nullable=True),
    sa.Column('human_reviewed', sa.Boolean(), nullable=False),
    sa.Column('sds_file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ambienti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('azienda_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('superficie_mq', sa.Numeric(), nullable=True),
    sa.Column('preposto_id', sa.UUID(), nullable=True),
    sa.Column('descrizione_attivita', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['azienda_id'], ['aziende.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preposto_id'], ['persone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persone_ambienti',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('ambiente_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambienti.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['persone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('persona_id', 'ambiente_id')
    )
    op.create_table('valutazioni_rischio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ambiente_id', sa.UUID(), nullable=False),
    sa.Column('categoria_rischio', sa.String(), nullable=False),
    sa.Column('applicabile', sa.Boolean(), nullable=False),
    sa.Column('pericolo', sa.Text(), nullable=True),
    sa.Column('condizioni_esposizione', sa.Text(), nullable=True),
    sa.Column('rischio', sa.Text(), nullable=True),
    sa.Column('misure_prevenzione', sa.Text(), nullable=True),
    sa.Column('probabilita_p', sa.Integer(), nullable=True),
    sa.Column('danno_d', sa.Integer(), nullable=True),
    sa.Column('indice_i', sa.Integer(), sa.Computed('2 * danno_d + probabilita_p', persisted=True), nullable=True),
    sa.Column('livello_rischio', sa.String(), sa.Computed("CASE WHEN (2 * danno_d + probabilita_p) <= 4 THEN 'ACCETTABILE' WHEN (2 * danno_d + probabilita_p) <= 6 THEN 'MODESTO' WHEN (2 * danno_d + probabilita_p) <= 8 THEN 'GRAVE' ELSE 'GRAVISSIMO' END", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambienti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valutazioni_rischio')
    op.drop_table('persone_ambienti')
    op.drop_table('ambienti')
    op.drop_table('sostanze_chimiche')
    op.drop_table('persone')
    op.drop_table('documenti_generati')
    op.drop_table('attrezzature')
    op.drop_table('users')
    op.drop_table('aziende')
    op.drop_table('organizations')
    # ### end Alembic commands ###
